services:
  Evrinoma\ContrAgentBundle\Controller\ContrAgentController:
    alias:  evrinoma.contr_agent.controller
    public: true

  evrinoma.contr_agent.controller:
    class: Evrinoma\ContrAgentBundle\Controller\ContrAgentController
    autowire: true

  Evrinoma\ContrAgentBundle\Controller\ContrAgentApiController:
    alias: evrinoma.contr_agent.api.controller
    public: true

  evrinoma.contr_agent.api.controller:
    class: Evrinoma\ContrAgentBundle\Controller\ContrAgentApiController
    arguments: ['@evrinoma.contr_agent.manager']
    autowire: true

  evrinoma.contr_agent.manager:
    alias: Evrinoma\ContrAgentBundle\Manager\ContrAgentManager

  Evrinoma\ContrAgentBundle\Manager\ContrAgentManager:
    arguments: ['@doctrine.orm.entity_manager', '%evrinoma.contr_agent.class%']

